// namespace JustinWritesCode.Common;
// using System.IO;

// public partial class RestoreCommonFiles
// {
//     public void RestoreDirectoryBuild(RestoredFiles restoredFilesRecords)
//     {
//         var directoryBuildPropsPath = Path.Combine(restoredFilesRecords.ProjectDirectory, "Directory.Build.props");
//         var directoryBuildTargetsPath = Path.Combine(restoredFilesRecords.ProjectDirectory, "Directory.Build.targets");
//         var packagesPath = Path.Combine(restoredFilesRecords.ProjectDirectory, "Packages.props");

//         var directoryBuildPropsFileInfo = new FileInfo(directoryBuildPropsPath);
//         var directoryBuildTargetsFileInfo = new FileInfo(directoryBuildTargetsPath);
//         var packagesFileInfo = new FileInfo(packagesPath);

//         var directoryBuildProps = directoryBuildPropsFileInfo.CreateText();
//         directoryBuildProps.WriteLine("<!-- This file is automatically generated by JustinWritesCode.Common.RestoreCommonFiles -->");
//         directoryBuildProps.WriteLine("<!-- Do not edit this file directly. -->");
//         directoryBuildProps.WriteLine("<!-- Instead, edit the file JustinWritesCode.Common.RestoreCommonFiles.cs and run the RestoreCommonFiles task. -->");
//         directoryBuildProps.WriteLine("<Project>");
//         directoryBuildProps.WriteLine($"  <Import Project=\"{Include}Directory.Build/*.props\" />");
//         directoryBuildProps.WriteLine("</Project>");
//         directoryBuildProps.Close();

//         var directoryBuildTargets = directoryBuildTargetsFileInfo.CreateText();
//         directoryBuildTargets.WriteLine("<!-- This file is automatically generated by JustinWritesCode.Common.RestoreCommonFiles -->");
//         directoryBuildTargets.WriteLine("<!-- Do not edit this file directly. -->");
//         directoryBuildTargets.WriteLine("<!-- Instead, edit the file JustinWritesCode.Common.RestoreCommonFiles.cs and run the RestoreCommonFiles task. -->");
//         directoryBuildTargets.WriteLine("<Project>");
//         directoryBuildTargets.WriteLine($"  <Import Project=\"{Include}Directory.Build/*.targets\" />");
//         directoryBuildTargets.WriteLine("</Project>");
//         directoryBuildTargets.Close();

//         var packagesFile = packagesFileInfo.CreateText();
//         packagesFile.WriteLine("<!-- This file is automatically generated by JustinWritesCode.Common.RestoreCommonFiles -->");
//         packagesFile.WriteLine("<!-- Do not edit this file directly. -->");
//         packagesFile.WriteLine("<!-- Instead, edit the file JustinWritesCode.Common.RestoreCommonFiles.cs and run the RestoreCommonFiles task. -->");
//         packagesFile.WriteLine("<Project>");
//         packagesFile.WriteLine($"  <Import Project=\"{Include}Packages/*.pkgs\" />");
//         packagesFile.WriteLine("</Project>");
//         packagesFile.Close();

//         var include = new DirectoryInfo(Include);

//         restoredFilesRecords.Files.Remove(restoredFilesRecords.Files.FirstOrDefault(file => file.Destination.FullName == directoryBuildPropsPath));
//         restoredFilesRecords.Files.Remove(restoredFilesRecords.Files.FirstOrDefault(file => file.Destination.FullName == directoryBuildTargetsPath));
//         restoredFilesRecords.Files.Remove(restoredFilesRecords.Files.FirstOrDefault(file => file.Destination.FullName == packagesPath));
//         // restoredFilesRecords.Files.Add(new RestoredFile(ProjectDirectoryInfo, include, directoryBuildPropsFileInfo, directoryBuildPropsFileInfo));
//         // restoredFilesRecords.Files.Add(new RestoredFile(ProjectDirectoryInfo, include, directoryBuildTargetsFileInfo, directoryBuildTargetsFileInfo));
//         // restoredFilesRecords.Files.Add(new RestoredFile(ProjectDirectoryInfo, include, packagesFileInfo, packagesFileInfo));
//     }
// }
